parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/'
  App\Identity\Domain\Repository\UserRepositoryInterface:
    alias: App\Identity\Infrastructure\Doctrine\Repository\UserRepository
