services:
  web:
    container_name: web
    image: web
    build:
      context: ./../web
      dockerfile: ./../docker/node/Dockerfile
    working_dir: /app
    volumes:
      - ./../web/:/app
      - /app/node_modules
    ports:
      - ${PORT_WEB}:5173
    command: sh -c "npm install && npm run dev -- --host"
  auth:
    container_name: auth
    image: auth
    build:
      context: ./../auth
      dockerfile: ./../docker/php/Dockerfile
    ports:
      - ${PORT_AUTH}:90
    volumes:
      - ./../auth/:/var/www/html
      - ./php/config/vhosts:/etc/apache2/sites-enabled
      - ./php/config/dir/dir.conf:/etc/apache2/mods-enabled/dir.conf
  auth_database:
    container_name: auth_database
    image: postgres:17.5
    environment:
      POSTGRES_DB: ${DATABASE_NAME_AUTH}
      POSTGRES_USER: ${DATABASE_USER_AUTH}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_AUTH}
  calendar:
    container_name: calendar
    image: calendar
    build:
      context: ./../calendar
      dockerfile: ./../docker/php/Dockerfile
    ports:
      - ${PORT_CALENDAR}:90
    volumes:
      - ./../calendar/:/var/www/html
      - ./php/config/vhosts:/etc/apache2/sites-enabled
      - ./php/config/dir/dir.conf:/etc/apache2/mods-enabled/dir.conf
